spring.application.name=shortener

spring.datasource.url=jdbc:mariadb://localhost:3306/shortener_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=shortener_usr
spring.datasource.password=shortner_pass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=250

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit_usr
spring.rabbitmq.password=rabbit_pass
spring.rabbitmq.virtual-host=/

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=50
